config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails, only: [:show, :new, :create, :index] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.valid?
      @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.valid?
      @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit button_label %>
<% end %>

app/views/cocktails/index.html.erb
<div class="pos-f-t">
  <nav class="navbar navbar-dark bg-dark">
    <p class="navbar-text">
      <h2 class="text-white">🍹 <%= link_to 'Monsieur Cocktail', cocktails_path %> 🍸</h2>
    </p>
  </nav>
</div>

<div class="container mt-3 pb-3">
  <div class="cards mt-3">
    <% @cocktails.each do |cocktail| %>
    <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1542849187-5ec6ea5e6a27?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60)">
      <%= link_to cocktail.name, cocktail_path(cocktail) %>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="pos-f-t">
  <nav class="navbar navbar-dark bg-dark">
    <p class="navbar-text">
      <h2 class="text-white">🍹 Monsieur Cocktail 🍸</h2>
    </p>
  </nav>
</div>

<div class="container">
  <h2>Create new cocktail</h2>
  <%= render 'form', button_label: 'Create!', cocktail: @cocktail %>
  <%= link_to 'Go back', cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<div class="pos-f-t">
  <nav class="navbar navbar-dark bg-dark">
    <p class="navbar-text">
      <h2 class="text-white">🍹 <%= link_to 'Monsieur Cocktail', cocktails_path %> 🍸</h2>
    </p>
  </nav>
</div>

<div class="container mt-3">
  <h3><%= @cocktail.name %></h3>
  <p>
    <%= cl_image_tag @cocktail.photo, crop: :fill %>
  </p>
  <div class="d-flex flex-column">
    <% @cocktail.doses.each do |doses| %>
    <ul>
      <li>
        <strong><%= doses.ingredient.name %></strong>: <%= doses.description %>
        (<%= link_to 'delete', dose_path(doses), method: :delete %>)
      </li>
    </ul>
    <% end %>
  </div>
  <p>
    <%= link_to "Add New Ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-info" %> or <%= link_to 'go back', cocktails_path %>
  </p>
</div>

app/views/doses/new.html.erb
<div class="pos-f-t">
  <nav class="navbar navbar-dark bg-dark">
    <p class="navbar-text">
      <h2 class="text-white">🍹 <%= link_to 'Monsieur Cocktail', cocktails_path %> 🍸</h2>
    </p>
  </nav>
</div>

<div class="container mt-3">
  <h3>Add new dose to <%= @cocktail.name %></h3>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: 'btn-primary' %>
  <% end %>

  <div>
    <br />
    <%= link_to 'Go back', cocktail_path(@cocktail), class: "btn btn-info" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monsieur Cocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <%= javascript_include_tag "application" %>
  <%= javascript_pack_tag "application" %>
</body>
</html>